### PR TITLE
chore: generate simpler lookups from ss58 registry

### PR DESCRIPTION
**Pull request by harrysolovay**
Should be useful for codegen purposes.

See lookups [here](https://github.com/paritytech/capi/blob/4400b66390eeb2bbcd85f826e415166adbb06d99/known/lookups.ts).

### CODE REVIEW

**Comment by tjjfvi** [comment]
I don't understand why this needs to be codegenned at all. Couldn't `lookups.ts` just be
```ts
import ss58Registry from "../deps/ss58_registry.ts";

export interface ChainInfo {
  prefix: number;
  network: string;
  displayName: string;
  symbols: string[];
  decimals: number[];
  standardAccount: string | null;
  website: string | null;
}

export const lookup: Record<string, ChainInfo> = Object.fromEntries(
  ss58Registry.map((obj) => [obj.network, obj]),
);
```

**Comment by harrysolovay** [comment]
Would be a tiny bit slower. Couldn't help but micro-optimize... in retrospect, the complexity of the build step might make this less worthwhile. Thoughts?

**Comment by tjjfvi** [comment]
Very tiny, and it's only ever run once. If anything, I would say optimize it by including the *specific* object in the codegen output (which would be as simple as `JSON.stringify(lookup[network])`)

**Comment by harrysolovay** [comment]
Closing in light of #260

**Pull request closed without merging**
