### PR TITLE
fix: enable dprint dep to be used offline

### LINKED ISSUE #423: import dprint dependency without runtime `fetch`

### PR DESCRIPTION
**Pull request by harrysolovay**
Fixes #423 

... sadly, we now depend on Shiki, which also stands in the way of offline runs :/ to-be-addressed in a another PR

### CODE REVIEW

**Comment by harrysolovay** [comment]
> We need to hex- or base64- encode the wasm and export it from a ts file.

I've updated the `_tasks/downloads.ts` script to generate a `util/tsFormatter.ts`, which includes the text-encoded, hex-encoded string of wasm... it's quite large (10_299_088 characters)... browsers will likely panic given that it's not instantiated via streaming. Feels like I'm complicating things. Gonna table this for now and return to it at a later date.

**Comment by tjjfvi** [comment]
> browsers will likely panic given that it's not instantiated via streaming

We only use dprint in the codegen server, so this shouldn't be an issue. Similar with `shiki` (hence why we're using `npm:shiki` for it).

**Comment by harrysolovay** [comment]
> We only use dprint in the codegen server, so this shouldn't be an issue

Very good point... we can revisit the browser-compat concern if we ever want to utilize the formatter for anything in `capi.dev`'s front end.

Meanwhile, `shiki` attempts to fetch the theme asset from a unpkg; this is a blocker to running the server offline. Any ideas for temporary fixes? (I'd imagine we'll think about alternative highlighting tools / potentially monaco in the longer term?)

**Review by tjjfvi — COMMENTED** [review]
Looks good, but the `deps/dprint_ts.wasm` should be deleted.

**Review by tjjfvi — APPROVED** [review]

**Review by tjjfvi — APPROVED** [review]

**Review by tjjfvi — APPROVED** [review]

**Pull request merged**
